version: '3'
services:
  pytorch113_dev:
    build:
      context: .
      dockerfile: dockerfile
      args:
        - GROUPNAME=key
        - GID=1000
        - USERNAME=key
        - UID=1000        
    volumes:
      - ../:/app
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: "key"
    tty: true
    working_dir: /app
